name: Check

on:
  push:
    branches: [ "main", "develop"]
  pull_request:
    branches: [ "main", "develop"]


jobs:
  First_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@master
    - name: Konstruktoid Python linting
    - uses: konstruktoid/action-pylint@master
         
             
  Second_check:
    needs: [ First_check ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 16.x
      - name: Setup Node.js environment
        run: |
         pwd
         ls -la
         pwd
         find . -name '*.pyc' -delete
         ls -la
      - name: Run a multi-line script
        run: |
          echo This section is under development,
          echo We apologize. 
      - uses: harupy/auto-labeling@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          label-pattern: '- \[(.*?)\] ?`(.+?)`'
