name: Check

on:
  push:
    branches: [ "main", "develop"]
  pull_request:
    branches: [ "main", "develop"]


jobs:
  First_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cclauss/Find-Python-syntax-errors-action@master
      - run: pip install bandit black codespell flake8 isort mypy pytest pyupgrade safety
      - run: bandit --recursive --skip B101 . || true  # B101 is assert statements
      - run: black --check . || true
      - run: codespell || true  # --ignore-words-list="" --skip=""
      - run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - run: flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --show-source --statistics
      - run: isort --check-only --profile black . || true
      - run: pip install -r requirements.txt || true
      - run: mypy --install-types --non-interactive . || true
      - run: pytest . || true
      - run: pytest --doctest-modules . || true
      - run: shopt -s globstar && pyupgrade --py36-plus **/*.py || true
      - run: safety check
  Second_check:
    needs: [ First_check ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 16.x
      - name: Setup Node.js environment
        run: |
         pwd
         ls -la
         pwd
         find . -name '*.pyc' -delete
         ls -la
      - name: Run a multi-line script
        run: |
          echo This section is under development,
          echo We apologize. 
      - uses: harupy/auto-labeling@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          label-pattern: '- \[(.*?)\] ?`(.+?)`'
