name: Test

on:
  
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  First_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Start!
  Second_test:
    needs: [ First_test ]
    runs-on: ubuntu-latest
      # Runs a set of commands using the runners shell
    steps:  
      - name: Setup Node.js environment
      - uses: actions/setup-node@v3.6.0
