name: Test

on:
  push:
    branches: [ "main", "develop"]
  pull_request:
    branches: [ "main", "develop"]


jobs:
  First_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: |
         pwd
         ls -la
         docker build .
         pwd
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  Second_test:
    needs: [ First_test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: |
         pwd
         ls -la
         echo Hello, world!
         pwd
         docker build .
         find . -name '*.pyc' -delete
         ls -la
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project. 
